services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    container_name: tunnel
    command: tunnel run
    env_file: .env
    environment:
      - TUNNEL_METRICS=0.0.0.0:60123
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:60123", "ready"]


# env has
# TUNNEL_TOKEN=

# there is no way to healthcheck this without building on this image
# its made using distroless debian
# an issue is put out for this:
# https://github.com/cloudflare/cloudflared/issues/1126

