services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    container_name: tunnel
    command: tunnel run
    env_file: .env

# env has
# TUNNEL_TOKEN=

# there is no way to healthcheck this without building on this image
# its made using distroless debian
# an issue is put out for this:
# https://github.com/cloudflare/cloudflared/issues/1126

