services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie
    restart: unless-stopped
    ports:
      - 9925:9000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ./data:/app/data

# default login
# changeme@email.com
# MyPassword