version: '3'
services:
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    # The following env vars are secret so set them within a .env file
    # - PLEX_CLAIM=
    env_file: .env
    volumes:
      - ./config:/config
      - /hdd/media/tv:/tv
      - /hdd/media/movies:/movies

