services:
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    ports:
     - 32400:32400
    healthcheck:
      test: nc -z 127.0.0.1 32400 || exit 1
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    # The following env vars are secret so set them within a .env file
    # - PLEX_CLAIM=
    env_file: .env
    volumes:
      - ./config:/config
      - /hdd/media/tv:/tv
      - /hdd/media/movies:/movies
