
version: '3'
services:
  reddit-top-rss:
    image: johnny5w/reddit-top-rss
    container_name: rssedit
    restart: unless-stopped
    ports:
      - 7076:8080
    env_file: .env
#    environment:
#      - REDDIT_USER=
#      - REDDIT_CLIENT_ID=your_app_id
#      - REDDIT_CLIENT_SECRET=your_app_secret
