version: "3.9"
services:
  redis:
    image: docker.io/library/redis
    restart: unless-stopped
    container_name: paperless_redis
    healthcheck:
      test: redis-cli ping
    volumes:
      - ./data:/data
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "7075:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: .env
#    user: "1000:1000"
    environment:
      PAPERLESS_REDIS: redis://redis
      COMPOSE_PROJECT_NAME: paperless
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: America/New_York
#      USERMAP_UID: 1000
#      USERMAP_GID: 1000
      # The following env vars are secret so set them within a .env file
      #PAPERLESS_ADMIN_PASSWORD=
      #PAPERLESS_ADMIN_USER=
      #PAPERLESS_URL=
      #PAPERLESS_SECRET_KEY=
