services:
  radarr: # https://hub.docker.com/r/linuxserver/radarr
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7878 || exit 1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ./movies:/movies
      - ./downloads:/downloads
#      - /hdd/media/movies:/movies
#      - /hdd/qbit:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped