version: "3.9"
services:
  bin:
    container_name: bin
    image: danielszabo99/microbin
    restart: unless-stopped
    ports:
     - 8081:8080
    volumes:
     - ./data:/app/microbin_data
# image does not have curl or wget or nc. making it difficult to healthcheck
# I submitted an issue to resolve this here:
# https://github.com/szabodanika/microbin/issues/240
#    healthcheck:
#      test: nc -z 127.0.0.1 8080 || exit 1
    env_file: .env
    environment:
      # additional as well as more details can be found at this url
      # https://raw.githubusercontent.com/szabodanika/microbin/master/.env
      MICROBIN_FOOTER_TEXT: "CodaBool's pastebin"
      MICROBIN_EDITABLE: "true"
      MICROBIN_HIDE_LOGO: "true"
      MICROBIN_NO_LISTING: "true"
      MICROBIN_HIGHLIGHTSYNTAX: "false"
      MICROBIN_PRIVATE: "true"
      MICROBIN_READONLY: "true"
      MICROBIN_SHOW_READ_STATS: "true"
      MICROBIN_GC_DAYS: 20 # default 90
      MICROBIN_ENABLE_BURN_AFTER: "true"
      MICROBIN_QR: "true"
      MICROBIN_DEFAULT_EXPIRY: "1hour" # 1min, 10min, 1hour, 24hour, 1week, never
      MICROBIN_ENCRYPTION_CLIENT_SIDE: "true"
      MICROBIN_ENCRYPTION_SERVER_SIDE: "true"
      MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB: 256
      MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB: 2048
      MICROBIN_DISABLE_TELEMETRY: "true"
      # The following env vars are secret so set them within a .env file
      # MICROBIN_ADMIN_USERNAME=
      # MICROBIN_ADMIN_PASSWORD=
      # MICROBIN_PUBLIC_PATH=https://
