services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 39762:39762
    # an openvpn config is also possible
    # I went with wiregaurd because it's more performant
    env_file: .env
    # environment:
    #   - VPN_SERVICE_PROVIDER=custom
    #   - VPN_TYPE=wireguard
    #   - VPN_ENDPOINT_IP=
    #   - VPN_ENDPOINT_PORT=51820
    #   - WIREGUARD_PUBLIC_KEY=
    #   - WIREGUARD_PRIVATE_KEY=
    #   - WIREGUARD_ADDRESSES=
  qbit:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbit
    network_mode: service:gluetun
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /hdd/downloads:/downloads
    restart: unless-stopped

# setup
# 1. set options > advanced to tun0 
# 2. update password (initial password is in qbit logs)
# 3. can use ipleak.net to check if leaking
