services:
  uptime:
    image: louislam/uptime-kuma
    container_name: uptime
    restart: unless-stopped
    ports:
    - 3001:3001
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
