version: "3"
services:
  watchtower:
    # https://containrrr.dev/watchtower/arguments
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400 # default 24 hours
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    command: bin watchtower sync rss rss_db jackett radarr plex sonarr proxy photoprism rssedit paperless paperless_redis mealie qbit jellyfin
