services:
  rss:
    # docs https://miniflux.app/docs/index.html
    image: miniflux/miniflux
    container_name: rss
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: /usr/bin/miniflux -healthcheck auto
    ports:
      - 8085:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POLLING_FREQUENCY=10 # default 60
      - BATCH_SIZE=100 # default 100
      - RUN_MIGRATIONS=1
  db:
    image: postgres
    restart: unless-stopped
    container_name: rss_db
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s

# environment variables
# https://miniflux.app/docs/configuration.html

# example .env
# POSTGRES_PASSWORD=
# CREATE_ADMIN=1 # only needed for first startup
# ADMIN_USERNAME=
# ADMIN_PASSWORD=
# DATABASE_URL=postgres://postgres:PASSWORD@rss_db/postgres?sslmode=disable


# This app frequently breaks due to postgres incompatibility
# Use this guide for upgrading major versions
# https://github.com/orgs/miniflux/discussions/2045#discussioncomment-7535806
