services:
  rss:
    # docs https://miniflux.app/docs/index.html
    image: miniflux/miniflux
    container_name: rss
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
    ports:
      - 8085:8080
    depends_on:
      - db
    environment:
      - POLLING_FREQUENCY=10 # default 60
      - BATCH_SIZE=100 # default 100
  db:
    image: postgres
    restart: unless-stopped
    container_name: rss_db
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s

# environment variables
# https://miniflux.app/docs/configuration.html

# example .env
# POSTGRES_PASSWORD=
# RUN_MIGRATIONS=1
# CREATE_ADMIN=1
# ADMIN_USERNAME=
# ADMIN_PASSWORD=
# DATABASE_URL=postgres://postgres:PASSWORD@rss_db/postgres?sslmode=disable