version: "3.5"
services:
  jackett: # https://hub.docker.com/r/linuxserver/jackett
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - AUTO_UPDATE=true
    volumes:
      - ./config:/config
      - ./downloads:/downloads # Path to torrent blackhole.
    ports:
      - 9117:9117
    restart: unless-stopped
