# usage
# https://rclone.org/commands/rclone_sync

# config folder is encrypted and owned by root 

run:
  docker run --rm --name rclone \
    -v ./data:/data \
    -v ./config:/config/rclone \
    rclone/rclone sync --verbose . proton:/sync

init:
  docker run -it \
    -v ./config:/config/rclone \
    rclone/rclone config
