services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /hdd/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped

# create these two folders inside the mounted media folder
# ensure that user 1000 has privilges for these
# - tv
# - movies
