services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=192.168.0.58 # optional
    volumes:
      - ./config:/config
#      - /hdd/media:/media
      - /hdd/media/tv:/data/tvshows
      - /hdd/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

# create these two folders inside the mounted media folder
# ensure that user 1000 has privilges for these
# - tv
# - movies
