version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: host
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /hdd/media:/media
    restart: unless-stopped

# create these two folders inside /hdd/media
# ensure that user 1000 has privilges for these
# - tv
# - movies
