services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: "TRUE"
      VERSION: "1.20.6"
#      MOD_PLATFORM: "MODRINTH"
    volumes:
      - ./data:/data

# change both of these to true in server.properties
#   white-list=true
#   enforce-whitelist=true

