services:
  sync:
    image: lscr.io/linuxserver/syncthing
    container_name: sync
    healthcheck:
      test: nc -z 127.0.0.1 8384 || exit 1
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - /hdd/sync:/sync
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped

