version: "3.9"
services:
  sync:
    image: lscr.io/linuxserver/syncthing
    container_name: sync
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - /hdd/sync:/sync
      - /home/codabool/foundry/star_wars/data:/star_wars_foundry
      - /home/codabool/foundry/data:/alien_foundry
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
