version: '3.9'
services:
  photoprism:
    image: photoprism/photoprism
    restart: unless-stopped
    container_name: photoprism
    env_file: .env
    ports:
      - 2342:2342
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:2342 || exit 1
    environment:
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (defaults to 1000Mb)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      # The following env vars are secret so set them within a .env file
      #PHOTOPRISM_ADMIN_USER= # defaults to admin
      #PHOTOPRISM_ADMIN_PASSWORD=
    user: "1000:1000"
    volumes:
      - /hdd/photos:/photoprism/originals
      - /hdd/photos/import:/photoprism/import                  # *Optional* base folder from which files can be imported to originals
      - ./storage:/photoprism/storage                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
