services:
  foundry:
    image: felddy/foundryvtt
    container_name: foundry
    healthcheck:
      test: curl --fail http://localhost:30000 || exit 1
    volumes:
      - ./data:/data
    env_file: .env
    environment:
      - FOUNDRY_GID=1000
      - FOUNDRY_UID=1000
      - FOUNDRY_HOT_RELOAD=true
# https://foundryvtt.com/releases/
      - FOUNDRY_VERSION=11.315
#      - FOUNDRY_VERSION=12.327
    ports:
      - 30000:30000
