services:
  foundry:
    image: felddy/foundryvtt
    container_name: foundry
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:30000 || exit 1
    volumes:
      - ./data:/data
    env_file: .env
    environment:
      - FOUNDRY_GID=1000
      - FOUNDRY_UID=1000
#      - FOUNDRY_HOT_RELOAD=true
# https://foundryvtt.com/releases/
      - FOUNDRY_VERSION=12.331
      - CONTAINER_PRESERVE_CONFIG=true
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - FOUNDRY_TELEMETRY=false
      - FOUNDRY_CSS_THEME=scifi
#      - FOUNDRY_VERSION=12.327
    ports:
      - 30000:30000
